### ISSUE TITLE
Some questions about the data

### ISSUE THREAD

**Issue by JamesCao2048** [wagner-group/diversevul#2]
Dear authors of DiverseVul,
I  am Junming Cao, a Ph.D. student in Fudan University. I have read your paper and found it very interesting and useful. However, I have several questions about the data.
1. DiverseVul was crawled from security issues, but these issues does not exist in the current available data. Are these issues available? 
2. I did not find fixed version code in the published data. Is only the original vulenrable code available?
3. How did you decide the CWE type of every vulnerable function?

Thanks!

**Comment by surrealyz** [comment]
Dear Junming,

Thanks for reaching out.

- We do not release the raw data, but we release the processed dataset in well-formatted and labeled json files.
- The non-vulnerable code has target value 0, and vulnerable code has target value 1.
- If any of the vulnerable function associated with a commit has a CVE number, we query the NIST CVE database to determine the CWE type.

Best,
Yizheng

**Comment by JamesCao2048** [comment]
Thanks a lot, it answered my questions perfectly!
Btw, will the raw data be released in the future, because I think the original issues are helpful for researchers who want to investigate them manually or developing models to utilize these additional information.

**Comment by surrealyz** [comment]
We don't have plans to release the raw data before the data processing. Thank you.
