### ISSUE TITLE
some question about dataset

### ISSUE THREAD

**Issue by pickwu** [wagner-group/diversevul#3]
Dear authors of DiverseVul,
The "DiverseVul" dataset contains two keys: "target" and "cwe." As I understand it, when "target" is equal to 1, it indicates that the code has vulnerabilities, and when "target" is equal to 0, the code is considered to be free of vulnerabilities. However, I have noticed that sometimes when "target" is 1, "cwe" is empty. Conversely, when "target" is 0, "cwe" has a value, indicating that the code belongs to a certain CWE vulnerability type. This has left me quite puzzled. Could you please provide some clarification? Thank you, kind sir!

**Comment by JasonDing0401** [comment]
Hi, thank you for reaching out! We use the same method that the ReVeal paper used to identify vulnerable and non-vulnerable functions. That is, we have unchanged functions as non-vulnerable and changed (fixed) functions as vulnerable.
Both functions will have the same CWE number because their **GitHub commit is related to a certain CWE**. And for some vulnerable functions we collected from security issue website (like bugzilla), their issue page does not include any CWE so we didn't include CWE for these functions.
I recommend reading section 3 data collection of our paper to get a clearer understanding.

**Comment by pickwu** [comment]
Dear authors of DiverseVul,
Thank you very much for your response. I understand what you mean. However, I have another question, and I hope you can help me with it. In the paper, it mentions the extraction of 18,945 vulnerable functions and 330,492 non-vulnerable functions. However, in the dataset, I found 18,945 functions with 'target=1,' which means vulnerable functions, and 311,547 functions with 'target=0,' which means non-vulnerable functions. This seems to be different from the numbers in the paper, but 18,945 + 311,547 = 330,492. This has left me somewhat puzzled.
Thank you, kind sir!

**Comment by ybdesire** [comment]
The paper write:
```
Our new dataset contains 18,945 vulnerable functions spanning 150 CWEs and 330,492 non-vulnerable functions extracted from 7,514 commits
```

And there are 330492 `"target"` at the dataset. 18945 `"target": 1`  and 311547 `"target": 0`. 

Do not care about that, only minor typo.  :)




> Dear authors of DiverseVul, Thank you very much for your response. I understand what you mean. However, I have another question, and I hope you can help me with it. In the paper, it mentions the extraction of 18,945 vulnerable functions and 330,492 non-vulnerable functions. However, in the dataset, I found 18,945 functions with 'target=1,' which means vulnerable functions, and 311,547 functions with 'target=0,' which means non-vulnerable functions. This seems to be different from the numbers in the paper, but 18,945 + 311,547 = 330,492. This has left me somewhat puzzled. Thank you, kind sir!

**Comment by ybdesire** [comment]
> Dear authors of DiverseVul, Thank you very much for your response. I understand what you mean. However, I have another question, and I hope you can help me with it. In the paper, it mentions the extraction of 18,945 vulnerable functions and 330,492 non-vulnerable functions. However, in the dataset, I found 18,945 functions with 'target=1,' which means vulnerable functions, and 311,547 functions with 'target=0,' which means non-vulnerable functions. This seems to be different from the numbers in the paper, but 18,945 + 311,547 = 330,492. This has left me somewhat puzzled. Thank you, kind sir!

Just FYI. The data at the table3 of the paper is correct.

**Comment by pickwu** [comment]
Dear authors of DiverseVul,
Thank you for your prompt response! I appreciate you taking the time to address and respond to my issue. Your insights have been very helpful to me.
