### ISSUE TITLE
What is the output of your llm fine-tuning?

### ISSUE THREAD

**Issue by ybdesire** [wagner-group/diversevul#4]
Did you use code ("func" at the data) as input and cwe  ("cwe" at the data) as output for LLM (such as CodeT5) fine tuning ?  Did you add any prompt ?  @surrealyz

**Comment by surrealyz** [comment]
We don't use the output from the LLM (such as CodeT5). We select the embedding in the LLM, and apply a linear layer to do prediction. We fine tune the entire model including the weights in the linear layer. Details of fine tuning can be found in the Section A.2 in the paper.
