### ISSUE TITLE
License

### ISSUE THREAD

**Issue by erex16** [wagner-group/diversevul#8]
Hello,

I am hoping to use this dataset as training data for an upcoming project, and I was wondering if you are planning to add a license to the repository soon? I see that the paper states there is a Creative Commons license but I wasn't sure if that was just for the paper or if it applied to the dataset as well. Thanks for your help.

**Comment by davidwagner** [comment]
Thank you for writing.  The paper is released under Creative Commons license.  The dataset is separate.  The dataset contains a collection of code segments written by others, and I would imagine that presumably whatever copyright license each segment of code was released under will apply to that segment of code.  We don't have the authority to apply some other license to code written by others.
